'use client';
import {investmentOverview} from '../../lib/finance.mjs';
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v);
export default function InvestmentPanel({data,connected,onEntry,onEquipment,onStock}){
 const f=investmentOverview(data);
 return <section className="investment-panel">
 <div className="panel-heading"><div><p className="eyebrow">DESDE O INÍCIO DO NEGÓCIO</p><h2>Investimento e retorno</h2><p className="footnote">Visão acumulada de todo o histórico, independente do filtro de período acima.</p></div><span className="badge">{f.pending?'Valores parciais':'Acumulado'}</span></div>
 <div className="stats"><div className="stat"><span>Aplicado em bens e estoque</span><strong>{money(f.applied)}</strong><small>Equipamentos, saldo inicial, compras e outros investimentos</small></div><div className="stat"><span>Vendas recebidas</span><strong>{money(f.received)}</strong><small>Recebimentos brutos; aportes ficam separados</small></div><div className="stat"><span>Lucro acumulado</span><strong className={f.profit<0?'negative':''}>{money(f.profit)}</strong><small>Resultado gerencial, inclusive vendas ainda a receber</small></div><div className="stat accent"><span>{f.balance>0?'Excedente de recuperação':'A recuperar pelos recebimentos'}</span><strong>{money(f.balance>0?f.surplus:f.remaining)}</strong><small>Considera saídas registradas e aquisições iniciais</small></div></div>
 {f.pending&&<p className="alert">Há materiais com custo pendente. O investimento e o valor a recuperar estão incompletos.</p>}
 <div className="dashboard-grid"><section className="panel"><h3>Recuperação pelos recebimentos</h3>{[['Recebimentos de vendas',f.received],['Saídas pagas registradas',-f.cashOut],['Aquisições iniciais fora do caixa',-f.initial],['Saldo de recuperação',f.balance]].map(([label,value])=><div className="list-row" key={label}><span>{label}</span><b className={value<0?'negative':''}>{money(value)}</b></div>)}<p className="footnote">Saldo negativo indica quanto falta recuperar com os registros atuais. Não é o prejuízo contábil nem o saldo bancário. Aportes e retiradas não alteram esta comparação. Gastos ainda não registrados podem mudar o resultado.</p></section>
 <section className="panel wear-panel"><h3>Meta de retorno pelo lucro</h3><div className="list-row"><span>Lucro / valor aplicado</span><b>{f.progress.toFixed(1).replace('.',',')}%</b></div><progress max="100" value={f.progress} aria-label="Meta de retorno pelo lucro"/><div className="list-row"><span>Lucro ainda necessário para a meta</span><b>{money(f.profitRemaining)}</b></div><p className="footnote">Comparação gerencial entre lucro acumulado e valor aplicado. O lucro já desconta material e amortização; esta meta não mede dinheiro recuperado e não deve ser somada ao saldo ao lado. O indicador visual fica entre 0% e 100%.</p></section></div>
 <section className="panel"><div className="panel-heading"><div><h3>Dinheiro do proprietário e caixa</h3><p className="footnote">Aporte é dinheiro colocado na empresa. Uma compra registra a aplicação desse dinheiro, sem contar o aporte como investimento novamente.</p></div></div><div className="investment-funding">{[['Aportes registrados',f.contributions],['Retiradas registradas',f.withdrawals],['Movimentação líquida de caixa',f.cash],['Vendas a receber (líquidas)',f.receivable]].map(([label,value])=><div key={label}><span>{label}</span><strong>{money(value)}</strong></div>)}</div><p className="footnote">Caixa = recebimentos + aportes − pagamentos − retiradas. O saldo inicial de bens não movimenta caixa. Sem o saldo bancário de abertura, esta é a movimentação registrada, não o saldo da conta.</p><div className="actions investment-actions"><button className="primary" disabled={!connected} onClick={()=>onEntry('aporte')}>＋ Aporte</button><button className="secondary" disabled={!connected} onClick={()=>onEntry('retirada')}>＋ Retirada</button><button className="secondary" disabled={!connected} onClick={()=>onEntry('despesa')}>＋ Despesa</button><button className="secondary" disabled={!connected} onClick={()=>onEntry('investimento')}>＋ Outro investimento</button><button className="secondary" disabled={!connected} onClick={onEquipment}>Cadastrar equipamento</button><button className="secondary" onClick={onStock}>Compras de estoque →</button></div></section>
 <section className="panel"><h3>De onde vem o valor aplicado</h3><p className="footnote">O custo inicial permanece no histórico mesmo depois do consumo do material. Equipamentos com pagamento vinculado são contados uma única vez. Ao cadastrar um equipamento, use a opção de pagamento do próprio cadastro; evite lançar a mesma aquisição novamente em “Outro investimento”.</p>{f.sources.length?<div className="table-scroll"><table><thead><tr><th>Item</th><th>Tipo</th><th>Registro</th><th>Valor aplicado</th></tr></thead><tbody>{f.sources.map(s=><tr key={s.id}><td>{s.name}</td><td>{s.kind}</td><td>{s.origin}</td><td>{s.pending?'Custo pendente':money(s.amount)}</td></tr>)}</tbody></table></div>:<p className="muted">Cadastre os equipamentos e as compras para acompanhar o investimento.</p>}</section>
 </section>;
}
