'use client';
import {useState,useRef,useEffect} from 'react';
import {depreciation,equipmentHours,maintenanceStatus} from '../../lib/maintenance.mjs';
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v);
const num=v=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:2}).format(v);
const day=()=>new Date().toLocaleDateString('en-CA');
const date=v=>String(v).slice(0,10).split('-').reverse().join('/');
const labels={ok:'Em dia',soon:'Em breve',due:'Vence agora',overdue:'Atrasada',paused:'Pausada'};
const rank={overdue:0,due:1,soon:2,ok:3,paused:4};
function Field({label,children,hint}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
function NumberInput({label,name,value,min=0,step='any',required=true,hint}){return <Field label={label} hint={hint}><input name={name} type="number" min={min} step={step} defaultValue={value} required={required}/></Field>}
export default function Maintenance({data,connected,busy,error,onSave,onAddEquipment}){
 const [selection,setSelection]=useState(''),[modal,setModal]=useState(null),[attempted,setAttempted]=useState(false),[today,setToday]=useState(day());const ref=useRef(null);
 const printers=data.equipment.filter(e=>e.kind==='impressora');const machine=printers.find(e=>e.id===selection)||printers[0];
 const plans=(data.maintenance_plans||[]).filter(p=>p.equipment_id===machine?.id).map(p=>({...p,status:maintenanceStatus(p,machine,today)})).sort((a,b)=>rank[a.status.state]-rank[b.status.state]);
 const history=(data.maintenance_logs||[]).filter(l=>l.equipment_id===machine?.id).sort((a,b)=>String(b.performed_on).localeCompare(String(a.performed_on))||String(b.created_at).localeCompare(String(a.created_at)));
 const hourLogs=(data.equipment_hour_logs||[]).filter(l=>l.equipment_id===machine?.id);
 const dep=machine?depreciation(machine):null;
 useEffect(()=>{const timer=setInterval(()=>setToday(day()),60000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(!modal)return;const el=ref.current,old=document.body.style.overflow;el.showModal();document.body.style.overflow='hidden';return()=>{el.close();document.body.style.overflow=old;};},[!!modal]);
 function open(action,plan=null){setAttempted(false);setModal({action,plan});}
 async function submit(e){e.preventDefault();setAttempted(true);const v=Object.fromEntries(new FormData(e.currentTarget));for(const k of ['active','recordExpense','affectsResult'])v[k]=v[k]==='on';const saved=await onSave({...v,action:modal.action,equipmentId:machine.id,...(modal.plan?{planId:modal.plan.id,version:modal.plan.version}:{})});if(saved)setModal(null);}
 const task=modal?.plan;
 return <div className="maintenance-page">
 {!machine?<section className="panel empty"><span>⚙</span><strong>Cadastre sua primeira impressora</strong><p>Depois, configure as tarefas e acompanhe o desgaste conforme as horas de uso.</p><button className="primary" disabled={!connected} onClick={onAddEquipment}>Cadastrar impressora</button></section>:<>
 <div className="maintenance-toolbar"><Field label="Impressora"><select value={machine.id} onChange={e=>setSelection(e.target.value)}>{printers.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><button className="secondary" disabled={!connected} onClick={()=>open('equipmentHours')}>＋ Horas anteriores / externas</button><button className="primary" disabled={!connected} onClick={()=>open('maintenancePlan')}>＋ Tarefa de manutenção</button></div>
 <div className="stats maintenance-stats"><div className="stat"><span>Uso acumulado</span><strong>{num(dep.hours)} h</strong><small>{num(machine.used_hours)} h de produção + {num(machine.prior_hours)} h anteriores / externas</small></div><div className="stat"><span>Depreciação por hora</span><strong>{money(dep.rate)}</strong><small>{money(machine.purchase_value)} ÷ {num(machine.life_hours)} horas</small></div><div className="stat"><span>Depreciação acumulada</span><strong>{money(dep.usedValue)}</strong><small>{num(dep.percent)}% do valor de aquisição</small></div><div className="stat accent"><span>Valor residual estimado</span><strong>{money(dep.remainingValue)}</strong><small>Estimativa gerencial pelo uso</small></div></div>
 <section className="panel wear-panel"><div className="panel-heading"><h2>Vida útil estimada pelo uso</h2><span>{num(dep.remainingHours)} h restantes</span></div><progress max="100" value={dep.percent} aria-label="Vida útil consumida"/><p className="footnote">O valor residual é limitado a zero. Atingir 100% não significa que a impressora parou de funcionar. Esta análise não lança uma nova despesa no financeiro: a amortização já faz parte do custo de produção.</p></section>
 <section className="panel"><div className="panel-heading"><div><h2>Cuidados programados</h2><p className="footnote">Com horas e dias configurados, vale o primeiro limite atingido.</p></div><span className="badge warn">{plans.filter(p=>['due','overdue'].includes(p.status.state)).length} pendentes</span></div>
 {plans.length?<div className="maintenance-tasks">{plans.map(p=><article className={'maintenance-task '+p.status.state} key={p.id}><div className="maintenance-task-head"><h3>{p.title}</h3><span className={'maintenance-status '+p.status.state}>{labels[p.status.state]}</span></div><div className="maintenance-limits">{p.status.nextHours!==null&&<div><span>Próxima referência</span><b>{num(p.status.nextHours)} h</b><small>{p.status.remainingHours<0?num(-p.status.remainingHours)+' h em atraso':p.status.remainingHours===0?'Limite de horas atingido':'Faltam '+num(p.status.remainingHours)+' h'}</small></div>}{p.status.nextOn&&<div><span>Próxima data</span><b>{date(p.status.nextOn)}</b><small>{p.status.remainingDays<0?-p.status.remainingDays+' dias em atraso':p.status.remainingDays===0?'Vence hoje':'Em '+p.status.remainingDays+' dias'}</small></div>}</div><p className="footnote">Referência: {date(p.baseline_on)} · {num(p.baseline_hours)} h</p>{p.notes&&<p className="maintenance-notes">{p.notes}</p>}<div className="actions"><button className="primary" disabled={!connected||!p.active} onClick={()=>open('maintenanceDone',p)}>Registrar realização</button><button className="secondary" disabled={!connected} onClick={()=>open('maintenanceUpdate',p)}>Configurar</button></div></article>)}</div>:<div className="empty"><strong>Nenhuma tarefa configurada para esta impressora.</strong><p>Crie tarefas para troca de bico, limpeza da placa, lubrificação ou outro cuidado. Os intervalos ficam sob seu controle.</p></div>}
 </section>
 <section className="panel"><h2>Histórico de manutenção</h2>{history.length?<div className="table-scroll"><table><thead><tr><th>Data</th><th>Tarefa / observações</th><th>Horímetro</th><th>Custo</th><th>Financeiro</th></tr></thead><tbody>{history.map(l=><tr key={l.id}><td>{date(l.performed_on)}</td><td><b>{l.title}</b><small>{l.notes||'—'}</small></td><td>{num(l.meter_hours)} h</td><td>{money(l.cost)}</td><td>{l.expense_recorded?'Pagamento registrado':'Sem novo lançamento'}</td></tr>)}</tbody></table></div>:<p className="muted">As tarefas realizadas aparecerão aqui com data, horas e observações.</p>}</section>
 {hourLogs.length>0&&<section className="panel"><h2>Horas adicionadas manualmente</h2><div className="table-scroll"><table><thead><tr><th>Registro</th><th>Horas</th><th>Motivo</th></tr></thead><tbody>{hourLogs.map(l=><tr key={l.id}><td>{new Date(l.created_at).toLocaleDateString('pt-BR')}</td><td>+ {num(l.added_hours)} h</td><td>{l.reason}</td></tr>)}</tbody></table></div></section>}
 <p className="footnote">Avisos aparecem nesta aba, no menu e na visão geral enquanto o sistema estiver aberto. O horímetro soma as produções finalizadas vinculadas à impressora, inclusive falhas. Ajuste os intervalos conforme o fabricante, o material e o seu uso.</p>
 </>}
 <dialog ref={ref} className="analysis-dialog maintenance-dialog" aria-labelledby="maintenance-dialog-title" onClose={()=>setModal(null)} onCancel={e=>{if(busy)e.preventDefault();else setModal(null);}}>{modal&&machine&&<><header className="analysis-dialog-header"><div><p className="eyebrow">MOLDAÊ · {machine.name}</p><h2 id="maintenance-dialog-title">{({maintenancePlan:'Nova tarefa',maintenanceUpdate:'Configurar tarefa',maintenanceDone:'Registrar manutenção',equipmentHours:'Adicionar horas de uso'})[modal.action]}</h2></div><button className="close" disabled={busy} onClick={()=>setModal(null)} aria-label="Fechar manutenção">×</button></header><form onSubmit={submit}><div className="analysis-dialog-content"><div className="form-grid">
 {['maintenancePlan','maintenanceUpdate'].includes(modal.action)&&<><Field label="Nome da tarefa"><input name="title" required maxLength="200" defaultValue={task?.title} list="maintenance-presets" placeholder="Ex.: Limpeza da placa de impressão"/><datalist id="maintenance-presets">{['Limpeza da placa de impressão','Inspeção / troca do bico','Lubrificação dos eixos','Verificação de correias','Limpeza dos ventiladores','Revisão geral'].map(t=><option key={t} value={t}/>)}</datalist></Field><NumberInput name="intervalHours" label="Repetir a cada (horas de uso)" value={task?.interval_hours??''} min="0.01" required={false}/><NumberInput name="intervalDays" label="Repetir a cada (dias)" value={task?.interval_days??''} min="1" step="1" required={false}/><NumberInput name="warnHours" label="Avisar com antecedência de (horas)" value={task?.warn_hours??0}/><NumberInput name="warnDays" label="Avisar com antecedência de (dias)" value={task?.warn_days??0} step="1"/>{!task&&<><NumberInput name="baselineHours" label="Horímetro na última manutenção / início" value={equipmentHours(machine)} hint={'Uso atual: '+num(equipmentHours(machine))+' h'}/><Field label="Data da última manutenção / início"><input name="baselineOn" type="date" max={today} defaultValue={today} required/></Field></>}<Field label="Instruções / observações"><textarea name="notes" rows="3" maxLength="2000" defaultValue={task?.notes} placeholder="Peça usada, orientação do fabricante ou cuidados específicos"/></Field>{task&&<label className="check"><input type="checkbox" name="active" defaultChecked={task.active}/> Manter avisos desta tarefa ativos</label>}<p className="form-note">Defina horas, dias ou ambos. Deixe em branco o limite que não quiser usar. A referência avança apenas quando você registra uma manutenção realizada.</p></>}
 {modal.action==='maintenanceDone'&&<><p className="form-note"><b>{task.title}</b> · {machine.name}</p><Field label="Data da realização"><input name="date" type="date" min={String(task.baseline_on).slice(0,10)} max={today} defaultValue={today} required/></Field><NumberInput name="meterHours" label="Horímetro na realização (horas)" value={equipmentHours(machine)} min={Number(task.baseline_hours)} hint={'No máximo '+num(equipmentHours(machine))+' h. Uma manutenção não zera o uso da máquina.'}/><NumberInput name="cost" label="Custo pago (R$)" value="0" step="0.01"/><Field label="O que foi feito"><textarea name="notes" rows="3" maxLength="2000" placeholder="Ex.: bico substituído, modelo da peça e observações"/></Field><label className="check"><input type="checkbox" name="recordExpense"/> Registrar este pagamento no financeiro</label><label className="check"><input type="checkbox" name="affectsResult"/> Descontar também do resultado (somente se este custo não estiver incluído nas peças)</label><p className="form-note">Registrar a realização atualiza a próxima referência desta tarefa e preserva o histórico. Não registre novamente um pagamento já lançado no financeiro.</p></>}
 {modal.action==='equipmentHours'&&<><p className="form-note">Uso atual: <b>{num(equipmentHours(machine))} h</b>. Informe somente horas que ainda não estão registradas. As produções do sistema são somadas automaticamente.</p><NumberInput name="hours" label="Horas a adicionar" min="0.01"/><Field label="Motivo"><input name="reason" required maxLength="200" placeholder="Ex.: 120 h de uso anterior ao cadastro"/></Field></>}
 </div>{attempted&&error&&<p className="alert error" role="alert">{error}</p>}</div><footer className="analysis-dialog-footer"><button type="button" className="secondary" disabled={busy} onClick={()=>setModal(null)}>Cancelar</button><button className="primary" disabled={busy}>{busy?'Salvando…':'Confirmar registro'}</button></footer></form></>}</dialog>
 </div>;
}
