import {PGlite} from '@electric-sql/pglite';import pg from 'pg';import {readFile} from 'node:fs/promises';import {randomUUID} from 'node:crypto';import {hashPassword,digest,token} from '../lib/auth.mjs';
export async function database(t){let db,admin,testName,p;
 if(process.env.TEST_REAL_POSTGRES==='1'){const url=process.env.ADMIN_DATABASE_URL||(await readFile('.local/admin.env','utf8')).split('\n').find(l=>l.startsWith('ADMIN_DATABASE_URL=')).slice(19);admin=new pg.Client({connectionString:url});await admin.connect();testName='moldae_security_'+Date.now();await admin.query('CREATE DATABASE '+testName);const u=new URL(url);u.pathname='/'+testName;p=new pg.Pool({connectionString:u.toString()});db={exec:s=>p.query(s),query:(...a)=>p.query(...a),close:()=>p.end()};}else db=new PGlite();
 t.after(async()=>{delete globalThis.atelierPool;await db.close();if(admin){await admin.query('DROP DATABASE '+testName+' WITH (FORCE)');await admin.end();}});
 await db.exec(await readFile(new URL('../db/001_initial.sql',import.meta.url),'utf8'));await db.exec(await readFile(new URL('../db/002_tenants.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../db/003_products.sql',import.meta.url),'utf8'));
 if(!(await db.query("SELECT 1 FROM pg_roles WHERE rolname='moldae_app'")).rows.length)await db.exec('CREATE ROLE moldae_app NOSUPERUSER NOBYPASSRLS');await db.exec('GRANT USAGE ON SCHEMA public TO moldae_app; GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO moldae_app');
 process.env.DATABASE_URL='postgres://test';globalThis.atelierPool={connect:async()=>{const c=p?await p.connect():{query:(...a)=>db.query(...a)};await c.query('SET ROLE moldae_app');return {query:(...a)=>c.query(...a),release:async()=>{await c.query('RESET ROLE');if(p)c.release();}}}};
 const tenant='00000000-0000-4000-8000-000000000001';const user=randomUUID();const secret=token();await db.query('INSERT INTO app_users(id,email,name,password_hash) VALUES($1,$2,$3,$4)',[user,'owner@example.test','Owner',await hashPassword('Testing-password-123!')]);await db.query("INSERT INTO memberships VALUES($1,$2,'owner')",[tenant,user]);await db.query("INSERT INTO sessions(token_hash,user_id,tenant_id,expires_at) VALUES($1,$2,$3,now()+interval '1 day')",[digest(secret),user,tenant]);return {db,tenant,user,cookie:'moldae_session='+secret};}
