import {database} from './database.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {POST,GET} from '../app/api/data/route.js';
test('PostgreSQL: compras → produção → venda → recebimento; estoque, falhas e duplicação',async(t)=>{
 const {db,cookie}=await database(t);
 async function post(payload,expected=201){const res=await POST(new Request('http://localhost/api/data',{method:'POST',headers:{'content-type':'application/json',origin:'http://localhost',cookie},body:JSON.stringify(payload)}));const body=await res.json();assert.equal(res.status,expected,JSON.stringify(body));return body;}
 const mat=await post({action:'material',name:'PLA azul',unit:'g',minimum:100});
 await post({action:'purchase',materialId:mat.id,quantity:1000,total:100,date:'2026-09-26'});
 await post({action:'purchase',materialId:mat.id,quantity:1000,total:200,date:'2026-09-26'});
 assert.equal(Number((await db.query('SELECT * FROM materials')).rows[0].unit_cost),.15);
 const equip=await post({action:'equipment',name:'Impressora',kind:'impressora',purchaseValue:1000,watts:200,lifeHours:1000,recordPayment:true,date:'2026-09-26'});
 const quote=await post({action:'quote',name:'Suporte',customer:'Cliente',input:{quantity:1,grams:100,kgPrice:150,hours:2,watts:200,kwh:1,machineValue:1000,lifeHours:1000,laborMinutes:30,hourRate:20,markupPercent:50}});
 const job=await post({action:'job',quoteId:quote.id,materialId:mat.id,equipmentId:equip.id});
 await post({action:'finish',jobId:job.id,status:'concluido',grams:3000,hours:2,laborMinutes:30,extras:0,date:'2026-09-26'},400);
 assert.equal(Number((await db.query('SELECT quantity FROM materials')).rows[0].quantity),2000);
 await post({action:'finish',jobId:job.id,status:'concluido',grams:100,hours:2,laborMinutes:30,extras:0,date:'2026-09-26'});
 await post({action:'finish',jobId:job.id,status:'concluido',grams:100,hours:2,laborMinutes:30,extras:0,date:'2026-09-26'},400);
 assert.equal(Number((await db.query('SELECT quantity FROM materials')).rows[0].quantity),1900);
 assert.equal(Number((await db.query('SELECT actual_cost FROM jobs')).rows[0].actual_cost),27.4);
 const sale=await post({action:'sale',jobId:job.id,amount:50,fees:5,date:'2026-09-26',paid:false});
 await post({action:'sale',jobId:job.id,amount:50,fees:5,date:'2026-09-26',paid:false},400);
 await post({action:'receive',saleId:sale.id,date:'2026-09-26'});
 await post({action:'receive',saleId:sale.id,date:'2026-09-26'},400);
 assert.equal((await db.query("SELECT * FROM entries WHERE kind='receita'")).rows.length,1);
 const failed=await post({action:'job',quoteId:quote.id,materialId:mat.id});
 await post({action:'finish',jobId:failed.id,status:'falha',grams:50,hours:1,laborMinutes:0,extras:0,date:'2026-09-26'});
 await post({action:'sale',jobId:failed.id,amount:50,fees:0,date:'2026-09-26'},400);
 await post({action:'entry',kind:'despesa',description:'Assinatura',amount:20,date:'2026-09-26',affectsResult:true});
 assert.equal((await db.query('SELECT * FROM entries WHERE affects_result=true')).rows.length,1);
 await post({action:'consume',materialId:mat.id,quantity:10,reason:'Perda avulsa',date:'2026-09-26'});
 assert.equal(Number((await db.query('SELECT quantity FROM materials')).rows[0].quantity),1840);
 await post({action:'materialUpdate',materialId:mat.id,name:'PLA Preto',unit:'g',minimum:150,brand:'eSun',color:'Preto',materialType:'PLA+',colorHex:'#25282a',imageUrl:'https://example.com/photo.jpg',sku:'PLA-TEST',location:'Caixa 1'});
 const edited=(await db.query('SELECT * FROM materials WHERE id=$1',[mat.id])).rows[0];assert.equal(edited.brand,'eSun');assert.equal(Number(edited.quantity),1840);
 await post({action:'material',name:'Inseguro',unit:'g',minimum:1,imageUrl:'javascript:alert(1)'},400);
 await post({action:'equipmentHours',equipmentId:equip.id,hours:98,reason:'Uso anterior ao cadastro'});
 assert.equal(Number((await db.query('SELECT prior_hours FROM equipment WHERE id=$1',[equip.id])).rows[0].prior_hours),98);
 const plan=await post({action:'maintenancePlan',equipmentId:equip.id,title:'Troca de bico',intervalHours:100,intervalDays:30,warnHours:10,warnDays:5,baselineHours:0,baselineOn:'2020-01-01'});
 await post({action:'maintenancePlan',equipmentId:equip.id,title:'Inválida',baselineHours:0,baselineOn:'2020-01-01'},400);
 await post({action:'maintenanceDone',planId:plan.id,version:0,date:'2020-01-02',meterHours:101,cost:35,recordExpense:true,affectsResult:true},400);
 await post({action:'maintenanceDone',planId:plan.id,version:0,date:'2020-01-02',meterHours:100,cost:35,recordExpense:true,affectsResult:true,notes:'Bico substituído'});
 await post({action:'maintenanceDone',planId:plan.id,version:0,date:'2020-01-02',meterHours:100,cost:35,recordExpense:true,affectsResult:true},400);
 assert.equal((await db.query('SELECT * FROM maintenance_logs')).rows.length,1);
 assert.equal((await db.query('SELECT * FROM entries WHERE source_id IN (SELECT id FROM maintenance_logs)')).rows.length,1);
 const updated=(await db.query('SELECT * FROM maintenance_plans WHERE id=$1',[plan.id])).rows[0];assert.equal(Number(updated.baseline_hours),100);assert.equal(updated.version,1);
 assert.equal(Number((await db.query('SELECT used_hours FROM equipment WHERE id=$1',[equip.id])).rows[0].used_hours),2);
 await post({action:'maintenanceUpdate',planId:plan.id,version:1,title:'Inspeção de bico',intervalHours:100,intervalDays:'',warnHours:10,warnDays:0,active:false});
 await post({action:'maintenanceDone',planId:plan.id,version:2,date:'2020-01-03',meterHours:100,cost:0},400);
 const initialMaterial=await post({action:'material',name:'PLA inicial',unit:'g',minimum:0});
 const entryCount=(await db.query('SELECT * FROM entries')).rows.length;
 await post({action:'openingStock',materialId:initialMaterial.id,quantity:1000});
 await post({action:'openingStock',materialId:initialMaterial.id,quantity:1000},400);
 let initialStock=(await db.query('SELECT * FROM materials WHERE id=$1',[initialMaterial.id])).rows[0];
 assert.equal(Number(initialStock.quantity),1000);assert.equal(initialStock.cost_pending,true);
 await post({action:'consume',materialId:initialMaterial.id,quantity:10,reason:'Perda avulsa',date:'2026-09-26'},400);
 await post({action:'purchase',materialId:initialMaterial.id,quantity:1000,total:100,date:'2026-09-26'},400);
 const pendingJob=await post({action:'job',quoteId:quote.id,materialId:initialMaterial.id});
 await post({action:'finish',jobId:pendingJob.id,status:'concluido',grams:10,hours:1,laborMinutes:0,extras:0,date:'2026-09-26'},400);
 await post({action:'openingCost',materialId:initialMaterial.id,total:90});
 await post({action:'openingCost',materialId:initialMaterial.id,total:90},400);
 initialStock=(await db.query('SELECT * FROM materials WHERE id=$1',[initialMaterial.id])).rows[0];
 assert.equal(Number(initialStock.quantity),1000);assert.equal(Number(initialStock.unit_cost),.09);assert.equal(initialStock.cost_pending,false);
 assert.equal((await db.query('SELECT * FROM entries')).rows.length,entryCount);
 assert.equal(Number((await db.query('SELECT unit_cost FROM movements WHERE material_id=$1',[initialMaterial.id])).rows[0].unit_cost),.09);
 const res=await GET(new Request('http://localhost/api/data',{headers:{cookie}}));assert.equal(res.status,200);const all=await res.json();assert.equal(all.materials.length,2);assert.equal(all.sales.length,1);
 const blocked=await POST(new Request('http://localhost/api/data',{method:'POST',headers:{origin:'http://evil.test'}}));assert.equal(blocked.status,403);
});
