import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {database} from './database.mjs';import {POST} from '../app/api/data/route.js';import {normalizeProduct,productQuote,resizeProductQuote} from '../lib/products.mjs';
test('Produto por mesas → orçamento de 3 unidades → estoque por cor → venda; isolamento e rollback',async t=>{
 const {db,cookie,tenant,user}=await database(t);
 async function post(payload,status=201){const res=await POST(new Request('http://localhost/api/data',{method:'POST',headers:{origin:'http://localhost',cookie,'Content-Type':'application/json'},body:JSON.stringify(payload)}));const body=await res.json();assert.equal(res.status,status,JSON.stringify(body));return body;}
 const a=await post({action:'material',name:'Branco',unit:'g',minimum:0}),b=await post({action:'material',name:'Marrom',unit:'g',minimum:0});for(const m of [a,b])await post({action:'purchase',materialId:m.id,quantity:1000,total:100,date:'2026-09-30'});
 const base={quantity:1,lifeHours:10000,watts:200,kwh:1,machineValue:1600,hourRate:15,laborMinutes:20,extras:2,markupPercent:50,sourceUrl:'https://makerworld.com/pt/models/2879353',plates:[{name:'Corpo',hours:2,materials:[{materialId:a.id,name:'Branco',grams:100,kgPrice:100}]},{name:'Cabeça',hours:1,materials:[{materialId:a.id,name:'Branco',grams:20,kgPrice:100},{materialId:b.id,name:'Marrom',grams:30,kgPrice:100}]}]};
 const product=await post({action:'product',name:'Jesus',input:base});const saved=(await db.query('SELECT * FROM products WHERE id=$1',[product.id])).rows[0];assert.equal(saved.input.grams,150);assert.equal(saved.input.hours,3);assert.equal(saved.input.materials.length,2);
 const input=productQuote(saved,3,(await db.query('SELECT * FROM materials')).rows);assert.equal(input.grams,450);assert.equal(input.hours,9);assert.equal(input.plates[1].materials[0].grams,60);assert.equal(resizeProductQuote(input,1).grams,150);
 const quote=await post({action:'quote',name:'Jesus 3 unidades',input});await post({action:'productUpdate',productId:product.id,name:'Alterado',input:{...base,plates:[base.plates[0]]}});assert.equal((await db.query('SELECT input FROM quotes WHERE id=$1',[quote.id])).rows[0].input.plates.length,2);
 const job=await post({action:'job',quoteId:quote.id});const finish={action:'finish',jobId:job.id,status:'concluido',materials:input.materials,hours:9,laborMinutes:60,extras:6,date:'2026-09-30'};
 await post({...finish,materials:input.materials.map(m=>({...m,grams:m.materialId===b.id?2000:m.grams}))},400);assert.equal(Number((await db.query('SELECT sum(quantity) AS n FROM materials')).rows[0].n),2000);assert.equal((await db.query('SELECT * FROM movements WHERE source_id=$1',[job.id])).rows.length,0);
 await post({...finish,materials:[input.materials[0],input.materials[0]]},400);await post(finish);await post(finish,400);assert.equal(Number((await db.query('SELECT quantity FROM materials WHERE id=$1',[a.id])).rows[0].quantity),640);assert.equal(Number((await db.query('SELECT quantity FROM materials WHERE id=$1',[b.id])).rows[0].quantity),910);assert.equal((await db.query('SELECT * FROM movements WHERE source_id=$1',[job.id])).rows.length,2);
 await post({action:'sale',jobId:job.id,amount:150,fees:0,paid:true,date:'2026-09-30'});assert.equal((await db.query('SELECT * FROM sales')).rows.length,1);
 const other=randomUUID(),foreign=randomUUID();await db.query("INSERT INTO tenants(id,name) VALUES($1,'Outra')",[other]);await db.query("INSERT INTO materials(id,name,unit,tenant_id) VALUES($1,'Privado','g',$2)",[foreign,other]);await post({action:'product',name:'Inválido',input:{...base,plates:[{name:'Teste',hours:1,materials:[{materialId:foreign,grams:1,kgPrice:100}]}]}},400);
 await db.query("UPDATE products SET tenant_id=$1 WHERE id=$2",[other,product.id]);await post({action:'productUpdate',productId:product.id,name:'Outro',input:base},404);await db.query("UPDATE memberships SET role='viewer' WHERE user_id=$1",[user]);await post({action:'product',name:'Negado',input:base},403);
 assert.throws(()=>normalizeProduct({...base,sourceUrl:'javascript:alert(1)'}));assert.throws(()=>normalizeProduct({...base,plates:[{...base.plates[0],hours:-1}]}));assert.throws(()=>normalizeProduct({...base,plates:[{...base.plates[0],materials:[base.plates[0].materials[0],base.plates[0].materials[0]]}]}));
});