import {readJson} from '../../../lib/http.mjs';
import {randomUUID} from 'node:crypto';import {transaction,tenantTransaction} from '../../../lib/db.mjs';import {validOrigin} from '../../../lib/request-origin.mjs';import {AuthError,authResponse,requireSession,email,label,hashPassword,verifyPassword,digest,token,throttle,newSession,sessionCookie,rawCookie} from '../../../lib/auth.mjs';
export const runtime='nodejs';export const dynamic='force-dynamic';
export async function GET(req){try{const s=await requireSession(req);const companies=await transaction(async c=>(await c.query('SELECT t.id,t.name,t.plan,t.status,m.role FROM memberships m JOIN tenants t ON t.id=m.tenant_id WHERE m.user_id=$1 ORDER BY t.name',[s.user_id])).rows);const members=s.role==='owner'?await transaction(async c=>(await c.query('SELECT u.id,u.name,u.email,m.role FROM memberships m JOIN app_users u ON u.id=m.user_id WHERE m.tenant_id=$1',[s.tenant_id])).rows):[];const audit=s.role==='owner'?await tenantTransaction(s,async c=>(await c.query('SELECT action,created_at FROM audit_events ORDER BY created_at DESC LIMIT 30')).rows):[];return Response.json({user:{id:s.user_id,name:s.name,email:s.email},company:{id:s.tenant_id,name:s.company,plan:s.plan,status:s.status},role:s.role,companies,members,audit},{headers:{'Cache-Control':'no-store'}});}catch(e){return authResponse(e);}}
export async function POST(req){if(!validOrigin(req))return Response.json({error:'Origem inválida.'},{status:403});try{if(Number(req.headers.get('content-length'))>12000)throw new AuthError('Pedido muito grande.',413);const b=await readJson(req,12000);if(!b||typeof b!=='object'||Array.isArray(b))throw new AuthError('Pedido inválido.',400);let raw,extra={};
 if(b.action==='login'){
 const address=email(b.email);await throttle('login:'+address);await throttle('login-global',100);
 raw=await transaction(async c=>{const user=(await c.query('SELECT * FROM app_users WHERE email=$1',[address])).rows[0];const encoded=user?.password_hash||'00000000000000000000000000000000:'+('00'.repeat(64));const valid=await verifyPassword(b.password,encoded);if(!user||!valid)throw new AuthError('E-mail ou senha inválidos.');const membership=(await c.query("SELECT m.tenant_id FROM memberships m JOIN tenants t ON t.id=m.tenant_id WHERE m.user_id=$1 AND t.status<>'suspended' ORDER BY t.created_at LIMIT 1",[user.id])).rows[0];if(!membership)throw new AuthError('Nenhuma empresa disponível para esta conta.',403);return newSession(c,user.id,membership.tenant_id);});
 }else if(['setup','accept','reset'].includes(b.action)){
 await throttle('token-global',100);if(!/^[a-f0-9]{64}$/.test(b.token||''))throw new AuthError('Link inválido ou expirado.',400);await throttle('token:'+b.token,8);const encoded=await hashPassword(b.password);
 raw=await transaction(async c=>{const kind=({setup:'setup',accept:'invite',reset:'reset'})[b.action];const t=(await c.query('SELECT * FROM auth_tokens WHERE token_hash=$1 AND kind=$2 AND used_at IS NULL AND expires_at>now() FOR UPDATE',[digest(b.token),kind])).rows[0];if(!t)throw new AuthError('Link inválido ou expirado.',400);
 const address=t.email||email(b.email);let user=(await c.query('SELECT * FROM app_users WHERE email=$1 FOR UPDATE',[address])).rows[0];
 if(kind==='reset'){if(!user)throw new AuthError('Link inválido ou expirado.',400);await c.query('UPDATE app_users SET password_hash=$1 WHERE id=$2',[encoded,user.id]);await c.query('DELETE FROM sessions WHERE user_id=$1',[user.id]);await c.query("UPDATE auth_tokens SET used_at=now() WHERE kind='reset' AND email=$1",[address]);await c.query('UPDATE auth_tokens SET used_at=now() WHERE token_hash=$1',[t.token_hash]);return null;}
 if(kind==='setup'&&(await c.query('SELECT 1 FROM memberships WHERE tenant_id=$1',[t.tenant_id])).rows.length)throw new AuthError('A empresa já possui administrador.',409);
 if(user){if(!await verifyPassword(b.password,user.password_hash))throw new AuthError('Esta conta já existe. Use sua senha atual para aceitar o convite.',400);}else{user={id:randomUUID()};await c.query('INSERT INTO app_users(id,email,name,password_hash) VALUES($1,$2,$3,$4)',[user.id,address,label(b.name),encoded]);}
 await c.query('INSERT INTO memberships(tenant_id,user_id,role) VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[t.tenant_id,user.id,t.role]);await c.query('UPDATE auth_tokens SET used_at=now() WHERE token_hash=$1',[t.token_hash]);return newSession(c,user.id,t.tenant_id);});
 }else if(b.action==='logout'){const value=rawCookie(req);if(value)await transaction(c=>c.query('DELETE FROM sessions WHERE token_hash=$1',[digest(value)]));raw='';
 }else{const s=await requireSession(req);
 if(b.action==='switch'){raw=await transaction(async c=>{const m=(await c.query("SELECT m.* FROM memberships m JOIN tenants t ON t.id=m.tenant_id WHERE m.user_id=$1 AND m.tenant_id=$2 AND t.status<>'suspended'",[s.user_id,b.tenantId])).rows[0];if(!m)throw new AuthError('Empresa indisponível.',403);await c.query('DELETE FROM sessions WHERE token_hash=$1',[s.token_hash]);return newSession(c,s.user_id,m.tenant_id);});}
 else if(b.action==='email'){await throttle('email:'+s.user_id,8);const address=email(b.email);raw=await transaction(async c=>{const u=(await c.query('SELECT * FROM app_users WHERE id=$1 FOR UPDATE',[s.user_id])).rows[0];if(!await verifyPassword(b.currentPassword,u.password_hash))throw new AuthError('Senha atual inválida.',400);if(address===u.email)throw new AuthError('Informe um e-mail diferente do atual.',400);if((await c.query('SELECT 1 FROM app_users WHERE email=$1',[address])).rows.length)throw new AuthError('Este e-mail não está disponível.',409);await c.query('UPDATE app_users SET email=$1 WHERE id=$2',[address,s.user_id]);await c.query('UPDATE auth_tokens SET used_at=now() WHERE email=$1 AND used_at IS NULL',[u.email]);await c.query('DELETE FROM sessions WHERE user_id=$1',[s.user_id]);return newSession(c,s.user_id,s.tenant_id);});}
 else if(b.action==='password'){await throttle('password:'+s.user_id,8);const encoded=await hashPassword(b.password);raw=await transaction(async c=>{const u=(await c.query('SELECT * FROM app_users WHERE id=$1 FOR UPDATE',[s.user_id])).rows[0];if(!await verifyPassword(b.currentPassword,u.password_hash))throw new AuthError('Senha atual inválida.',400);await c.query('UPDATE app_users SET password_hash=$1 WHERE id=$2',[encoded,s.user_id]);await c.query("UPDATE auth_tokens SET used_at=now() WHERE kind='reset' AND email=$1 AND used_at IS NULL",[u.email]);await c.query('DELETE FROM sessions WHERE user_id=$1',[s.user_id]);return newSession(c,s.user_id,s.tenant_id);});}
 else if(b.action==='invite'){await requireSession(req,true);await throttle('invite:'+s.user_id,20);const address=email(b.email);if(!['owner','viewer'].includes(b.role))throw new AuthError('Permissão inválida.',400);const invitation=token();await transaction(c=>c.query("INSERT INTO auth_tokens(token_hash,kind,tenant_id,email,role,expires_at) VALUES($1,'invite',$2,$3,$4,now()+interval '48 hours')",[digest(invitation),s.tenant_id,address,b.role]));extra={inviteToken:invitation};}
 else if(b.action==='revokeInvites'){await requireSession(req,true);await transaction(c=>c.query("UPDATE auth_tokens SET used_at=now() WHERE tenant_id=$1 AND kind='invite' AND used_at IS NULL",[s.tenant_id]));}
 else if(b.action==='removeMember'){await requireSession(req,true);if(b.userId===s.user_id)throw new AuthError('Você não pode remover seu próprio acesso.',400);await transaction(async c=>{await c.query("UPDATE auth_tokens SET used_at=now() WHERE tenant_id=$1 AND kind='invite' AND email=(SELECT email FROM app_users WHERE id=$2)",[s.tenant_id,b.userId]);await c.query('DELETE FROM memberships WHERE tenant_id=$1 AND user_id=$2',[s.tenant_id,b.userId]);await c.query('DELETE FROM sessions WHERE tenant_id=$1 AND user_id=$2',[s.tenant_id,b.userId]);});}
 else throw new AuthError('Ação inválida.',400);
 await tenantTransaction(s,c=>c.query('INSERT INTO audit_events(id,actor_id,action) VALUES($1,$2,$3)',[randomUUID(),s.user_id,'account.'+b.action]));
 }
 const headers={'Cache-Control':'no-store'};if(raw!==undefined)headers['Set-Cookie']=sessionCookie(raw||'');return Response.json({ok:true,...extra}, {headers});
 }catch(e){return authResponse(e);}}
