import {randomBytes,randomUUID,createHash,scrypt as scryptCb,timingSafeEqual} from 'node:crypto';
import {promisify} from 'node:util';import {transaction,tenantTransaction} from './db.mjs';
const scrypt=promisify(scryptCb);export const cookieName='moldae_session';
export const digest=v=>createHash('sha256').update(v).digest('hex');export const token=()=>randomBytes(32).toString('hex');
export class AuthError extends Error{constructor(message,status=401){super(message);this.status=status;}}
export function email(v){if(typeof v!=='string'||v.length>254||!/^\S+@\S+\.\S+$/.test(v))throw new AuthError('Informe um e-mail válido.',400);return v.trim().toLowerCase();}
export function label(v){if(typeof v!=='string'||!v.trim()||v.length>200)throw new AuthError('Preencha o nome (até 200 caracteres).',400);return v.trim();}
export async function hashPassword(v){if(typeof v!=='string'||v.length<12||v.length>128)throw new AuthError('Use uma senha entre 12 e 128 caracteres.',400);const salt=randomBytes(16).toString('hex');const hash=await scrypt(v,salt,64,{N:32768,r:8,p:1,maxmem:67108864});return salt+':'+hash.toString('hex');}
export async function verifyPassword(value,encoded){if(typeof value!=='string'||value.length>128)return false;const [salt,hex]=encoded.split(':');const calculated=await scrypt(value,salt,64,{N:32768,r:8,p:1,maxmem:67108864});const expected=Buffer.from(hex,'hex');return expected.length===calculated.length&&timingSafeEqual(expected,calculated);}
export async function throttle(key,max=10){const count=await transaction(async c=>(await c.query("INSERT INTO auth_attempts(bucket,count,expires_at) VALUES($1,1,now()+interval '15 minutes') ON CONFLICT(bucket) DO UPDATE SET count=CASE WHEN auth_attempts.expires_at<now() THEN 1 ELSE auth_attempts.count+1 END,expires_at=CASE WHEN auth_attempts.expires_at<now() THEN now()+interval '15 minutes' ELSE auth_attempts.expires_at END RETURNING count",[digest(key)])).rows[0].count);if(count>max)throw new AuthError('Muitas tentativas. Aguarde 15 minutos.',429);}
export function rawCookie(req){const value=req.headers.get('cookie')?.split(';').map(v=>v.trim()).find(v=>v.startsWith(cookieName+'='))?.slice(cookieName.length+1);return /^[a-f0-9]{64}$/.test(value||'')?value:null;}
export async function requireSession(req,write=false){const raw=rawCookie(req);if(!raw)throw new AuthError('Entre na sua conta.');return transaction(async c=>{const s=(await c.query("SELECT s.token_hash,s.user_id,s.tenant_id,u.email,u.name,m.role,t.name AS company,t.plan,t.status FROM sessions s JOIN app_users u ON u.id=s.user_id JOIN memberships m ON m.user_id=s.user_id AND m.tenant_id=s.tenant_id JOIN tenants t ON t.id=s.tenant_id WHERE s.token_hash=$1 AND s.expires_at>now() AND s.last_seen>now()-interval '12 hours'",[digest(raw)])).rows[0];if(!s)throw new AuthError('Sessão expirada. Entre novamente.');if(s.status==='suspended')throw new AuthError('Acesso da empresa suspenso. Contate o administrador.',403);if(write&&(s.role!=='owner'||s.status!=='active'))throw new AuthError('Esta conta tem acesso somente de leitura.',403);await c.query('UPDATE sessions SET last_seen=now() WHERE token_hash=$1',[s.token_hash]);return s;});}
export async function newSession(c,userId,tenantId){const raw=token();await c.query("INSERT INTO sessions(token_hash,user_id,tenant_id,expires_at) VALUES($1,$2,$3,now()+interval '7 days')",[digest(raw),userId,tenantId]);return raw;}
export function sessionCookie(raw){const secure=(process.env.APP_ORIGIN||'').startsWith('https:');return cookieName+'='+raw+'; HttpOnly; SameSite=Lax; Path=/; Max-Age='+(raw?604800:0)+(secure?'; Secure':'');}
export function authResponse(e){if(e instanceof AuthError)return Response.json({error:e.message},{status:e.status,headers:{'Cache-Control':'no-store'}});console.error('Falha de autenticação:',e.code||e.name);return Response.json({error:'Não foi possível concluir. Tente novamente.'},{status:500});}
export async function audit(s,action,entityId=null){return tenantTransaction(s,c=>c.query('INSERT INTO audit_events(id,actor_id,action,entity_id) VALUES($1,$2,$3,$4)',[randomUUID(),s.user_id,action,entityId]));}
