import {calculate} from './calculate.mjs';
export function resizeProductQuote(input,quantity){const count=Number(quantity),previous=Number(input.quantity);if(!Number.isInteger(count)||count<1||count>100000||!Number.isInteger(previous)||previous<1)throw Error('Quantidade deve ser um inteiro positivo.');const result={...input,quantity:count};for(const key of ['grams','hours','laborMinutes','extras'])result[key]=Number(input[key]||0)/previous*count;if(input.plates)result.plates=input.plates.map(p=>({...p,hours:Number(p.hours)/previous*count,materials:p.materials.map(m=>({...m,grams:Number(m.grams)/previous*count}))}));if(input.materials)result.materials=input.materials.map(m=>({...m,grams:Number(m.grams)/previous*count}));calculate(result);return result;}
export function productQuote(product,quantity,materials=[],equipment=[]){const input=resizeProductQuote(normalizeProduct(product.input),quantity);if(input.materials){input.materials=input.materials.map(m=>{const stock=materials.find(x=>x.id===m.materialId);if(!stock||stock.cost_pending)throw Error('Confira o cadastro e custo de todos os filamentos.');return {...m,name:stock.name,kgPrice:Number(stock.unit_cost)*1000};});if(input.plates)input.plates=input.plates.map(p=>({...p,materials:p.materials.map(m=>({...m,...input.materials.find(x=>x.materialId===m.materialId),grams:m.grams}))}));input.grams=input.materials.reduce((sum,m)=>sum+Number(m.grams),0);input.materialId=input.materials[0].materialId;}const material=materials.find(m=>m.id===input.materialId);const machine=equipment.find(m=>m.id===input.equipmentId);if(material){if(material.cost_pending)throw Error('Informe o custo do filamento no estoque antes de orçar.');input.kgPrice=Number(material.unit_cost)*1000;}if(machine)Object.assign(input,{watts:Number(machine.watts),machineValue:Number(machine.purchase_value),lifeHours:Number(machine.life_hours)});return {...input,productId:product.id,productName:product.name};}

export function normalizeProduct(input){
 const result={...input};
 if(input.sourceUrl){let url;try{url=new URL(input.sourceUrl);}catch{throw Error('Link do modelo inválido.');}if(url.protocol!=='https:'||url.username||url.password||url.href.length>2000)throw Error('Use um link HTTPS válido.');result.sourceUrl=url.href;}
 if(input.plates!==undefined){if(!Array.isArray(input.plates)||!input.plates.length||input.plates.length>100)throw Error('Cadastre entre 1 e 100 mesas.');const totals=new Map();let hours=0;
 result.plates=input.plates.map((p,i)=>{if(typeof p.name!=='string'||!p.name.trim()||p.name.length>200)throw Error('Informe o nome de cada mesa.');const time=Number(p.hours);if(p.hours===''||!Number.isFinite(time)||time<0)throw Error('Tempo de mesa inválido.');if(!Array.isArray(p.materials)||!p.materials.length||p.materials.length>30)throw Error('Informe os filamentos de cada mesa.');const seen=new Set();const materials=p.materials.map(m=>{const grams=Number(m.grams),kgPrice=Number(m.kgPrice);if(!m.materialId||seen.has(m.materialId)||m.grams===''||!Number.isFinite(grams)||grams<0||!Number.isFinite(kgPrice)||kgPrice<0)throw Error('Confira os filamentos e consumos de cada mesa.');seen.add(m.materialId);const part={materialId:m.materialId,name:String(m.name||'').slice(0,200),grams,kgPrice};const old=totals.get(m.materialId);if(old&&old.kgPrice!==kgPrice)throw Error('O mesmo filamento deve ter o mesmo custo em todas as mesas.');totals.set(m.materialId,{...part,grams:grams+(old?.grams||0)});return part;});hours+=time;return {name:p.name.trim(),hours:time,materials};});
 result.materials=[...totals.values()];result.hours=hours;result.grams=result.materials.reduce((sum,m)=>sum+m.grams,0);result.materialId=result.materials[0].materialId;
 }
 calculate(result);return result;
}
